### ISSUE TITLE
Que versión de openshift soporta?

### ISSUE THREAD

**Issue by rmacian** [mvilche/apache-kafka-openshift#2]
Estoy en openshift 3.11 y he hecho un fork del repositorio para instalar 2.4.1, después de la configuración desde la rama production y al arrancar el pod de kafka aparece el siguiente error:

```
.
.
bool ZStallOnOutOfMemory                      = true                                      {product} {default}
     uint ZStatisticsInterval                      = 10                                        {product} {default}
     bool ZeroTLAB                                 = false                                     {product} {default}
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: while parsing a block mapping
 in 'reader', line 2, column 1:
    lowercaseOutputName: true
    ^
expected <block end>, but found BlockEntry
 in 'reader', line 15, column 1:
    - pattern : kafka.server<type=(. ...
    ^

        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
        at io.prometheus.jmx.shaded.org.yaml.snakeyaml.Yaml.load(Yaml.java:393)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:74)
        at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
```

**Comment by rmacian** [comment]
There are trailing spaces that causes the yaml to be in wrong format

```
      kind: ConfigMap$
      metadata:$
        name: jmx-exporter-zoo        $
$
```

**Comment by rmacian** [comment]
Hay errores en el identado del fichero jmx

he realizado una PR para que se vean los fallos aunque esta apunta a mi fork

https://github.com/mvilche/apache-kafka-openshift/pull/3

**Comment by mvilche** [comment]
Hola.
Está testeado en Origin 3.6 y 3.11.
El error te está dando al desplegar el template o al levantar el servicio de zookeeper?

**Comment by mvilche** [comment]
Estoy probando el despliegue en 3.11 y no puedo detectar los errores al desplegar el template
Qué versión del cliente oc estás utilizando?

oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
➜  apache-kafka-openshift git:(production) oc new-app -f apache-kafka-openshift-template.yaml -p NAMESPACE=kafka -n kafka
--> Deploying template "kafka/kafka-zookeeper-openshift-mvilche" for "apache-kafka-openshift-template.yaml" to project kafka

     kafka-zookeeper-openshift-mvilche
     ---------
     APACHE KAFKA + ZOOKEEPER + KAFKA MANAGER WEB Martin Fabrizzio Vilche. https://github.com/mvilche.

     Los servicios iniciarán en unos minutos... -------------------------------------------------------------- Grafana
     Usuario admin Password admin
     --------------------------------------------------------------
     Martin Fabrizzio Vilche           

     * With parameters:
        * Nombre del proyecto donde esta desplegando el template. Respete maysculas y minúsculas=kafka

--> Creating resources ...
    configmap "zookeeper" created
    service "zookeeper" created
    statefulset.apps "zookeeper" created
    service "kafka" created
    statefulset.apps "kafka" created
    buildconfig.build.openshift.io "kafka" created
    imagestream.image.openshift.io "kafka" created
    buildconfig.build.openshift.io "zookeeper" created
    imagestream.image.openshift.io "zookeeper" created
    buildconfig.build.openshift.io "kafka-exporter" created
    imagestream.image.openshift.io "kafka-exporter" created
    deploymentconfig.apps.openshift.io "kafka-exporter" created
    service "kafka-exporter" created
    route.route.openshift.io "kafka-exporter-http" created
    deploymentconfig.apps.openshift.io "kafka-manager" created
    service "kafka-manager" created
    route.route.openshift.io "kafka-manager-http" created
    buildconfig.build.openshift.io "kafka-manager-sbt" created
    imagestream.image.openshift.io "kafka-manager-sbt" created
    buildconfig.build.openshift.io "kafka-manager" created
    imagestream.image.openshift.io "kafka-manager" created
    configmap "kafka-manager" created
    configmap "jmx-exporter-zoo" created
    configmap "jmx-exporter-kafka" created
    configmap "grafana-config" created
    configmap "grafana-config-datasource" created
    configmap "grafana-config-dashboard" created
    configmap "prometheus-config" created
    deploymentconfig.apps.openshift.io "prometheus" created
    service "prometheus" created
    buildconfig.build.openshift.io "prometheus" created
    imagestream.image.openshift.io "prometheus" created
    deploymentconfig.apps.openshift.io "grafana" created
    service "grafana" created
    route.route.openshift.io "grafana-http" created
    route.route.openshift.io "prometheus-http" created
    buildconfig.build.openshift.io "grafana" created
    imagestream.image.openshift.io "grafana" created
    persistentvolumeclaim "grafana-prom-data" created
--> Success
    Build scheduled, use 'oc logs -f bc/kafka' to track its progress.
    Build scheduled, use 'oc logs -f bc/zookeeper' to track its progress.
    Build scheduled, use 'oc logs -f bc/kafka-exporter' to track its progress.
    Access your application via route 'kafka-exporter-http-kafka.127.0.0.1.nip.io' 
    Access your application via route 'kafka-manager-http-kafka.127.0.0.1.nip.io' 
    Build scheduled, use 'oc logs -f bc/kafka-manager-sbt' to track its progress.
    Build scheduled, use 'oc logs -f bc/kafka-manager' to track its progress.
    Build scheduled, use 'oc logs -f bc/prometheus' to track its progress.
    Access your application via route 'grafana-http-kafka.127.0.0.1.nip.io' 
    Access your application via route 'prometheus-http-kafka.127.0.0.1.nip.io' 
    Build scheduled, use 'oc logs -f bc/grafana' to track its progress.
    Run 'oc status' to view your app.
➜  apache-kafka-openshift git:(production)

**Comment by mvilche** [comment]
El problema que vi de indentado es en el jmx exporter del kafka.
Quedó solucionado.
Si tienes algún tema con la instalación no dudes en avisarme.

Saludos

**Comment by mvilche** [comment]
adicionalmente agregue otro fix al template, en el build config estaba referenciando al branch develop y no el de production.

**Comment by mvilche** [comment]
Pudiste iniciar el proyecto?

**Comment by rmacian** [comment]
si ,con  esos cambios que mostre en la PR pude hacerlo. Hay otro tema que he tenido que hacer para poder acceder a esos kafka desde el exterior y implementé la solución 3 que se puede ver aquí:

https://argus-sec.com/external-communication-with-apache-kafka-deployed-in-kubernetes-cluster/

que consiste en crear 3 servicios que apuntan a cada uno de los pods por el label.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
  labels:
    app: kafka-zookeeper-kafkamanager
spec:
  ports:
    - port: 9092
      name: server0
  type: ClusterIP
  selector:
    service: kafka
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
  labels:
    app: kafka-zookeeper-kafkamanager
spec:
  ports:
    - port: 9092
      name: kafka
  type: ClusterIP
  selector:
    service: kafka
    statefulset.kubernetes.io/pod-name: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
  labels:
    app: kafka-zookeeper-kafkamanager
spec:
  ports:
    - port: 9092
      name: kafka
  type: ClusterIP
  selector:
    service: kafka
    statefulset.kubernetes.io/pod-name: kafka-2
```

a partir de ahi se les puede asignar una ip externa del pool

**Comment by mvilche** [comment]
Ok bien.

Ya puedes acceder a cada broker de esta forma:

kafka-0.kafka.$NAMESPACE.svc.cluster.local:9092
kafka-1.kafka.$NAMESPACE.svc.cluster.local:9092
kafka-2.kafka.$NAMESPACE.svc.cluster.local:9092

No es necesario que definas un servicio por cada instancia.

Saludos!
